name: CI
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@5
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@4
      - uses: actions/setup-node@6
        with:
          node-version: 24.10.0
          cache: pnpm
      - run: pnpm install
      - run: pnpm --filter astro-typed-ids build