name: Release
permissions: {}
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'florian-lefebvre' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false
      - uses: pnpm/action-setup@4
      - uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
          cache: 'pnpm'
      - run: pnpm install
      - name: Create Release Pull Request
        uses: changesets/action@1
        with:
          version: pnpm ci-version
          publish: pnpm ci-publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: "" # See https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868